### ISSUE TITLE
Is there way to put numbers only captcha

### ISSUE THREAD

**Issue by zuhairkareem** [masroorejaz/react-simple-captcha#10]
I have seen in the documentation that it allows for uppercase+numbers or lowercase+numbers, Is there way to put numbers only captcha

**Comment by masroorejaz** [comment]
Hello,

I have add support for both numbers only and special characters only support in my latest version 8.2.0

Also updated the documentation. Kindly read the documentation to know how to implement it.

Best Regards,
Masroor Ejaz.

**Comment by zuhairkareem** [comment]
Thanks for the update and for the wonderful library

**Comment by masroorejaz** [comment]
Thank you so much!

Kindly rate react-simple-captcha at the following link:
https://openbase.com/js/react-simple-captcha#rate

It will only take a few minutes. Thank you :)
