### ISSUE TITLE
It doesn't support .TSX

### ISSUE THREAD

**Issue by SolManali** [masroorejaz/react-simple-captcha#14]
I tried to use the plugin on my .tsx but it doesn't support it. The error is "Could not find a declaration file for module 'react-simple-captcha'"

**Comment by SolManali** [comment]
I Use next.js.

There's also an error if i continue with the warning:

C"annot use import statement outside a module"

**Comment by masroorejaz** [comment]
Hello,

I still haven't make it compatible with next.js or typescript yet.

I will do when I will get some free time.

Meanwhile all the code is on github you can try converting it to next.js by your self

Thank you.
