### ISSUE TITLE
Extract code image / send it in email

### ISSUE THREAD

**Issue by Jozsef88** [masroorejaz/react-simple-captcha#15]
I would like the generated code, which is obviously burnt in a picture, send in email.
Is there a way to do that?

So I have set the 'loadCaptchaEngine' and the <LoadCanvasTemplate /> and I want to send the appearing code in email. I know how to send email in my code, I just want to extract the picture/code somehow.

Could you please tell me how I can acquire that?

**Comment by masroorejaz** [comment]
Hello,

No it's not possible since everytime you reload the captcha it's value changes.

You need to make simple changes in code (available on GitHub) to make this happen.

For any other questions feel free to contact me.

Thank you.
