### ISSUE TITLE
Not Working in Nextjs Even Turned off SSR

### ISSUE THREAD

**Issue by totalard** [masroorejaz/react-simple-captcha#19]
It just say 

```
Server Error
SyntaxError: Cannot use import statement outside a module
```

**Comment by masroorejaz** [comment]
Currently it is not compatible with Nextjs or Type Script.

If I will get some free time in the future I will definitely make it compatible with both. Also my code if available on GitHub so you or any other talented developer can make it compatible with both frameworks.

Thank you.
