### ISSUE TITLE
Doesn't work in React 18

### ISSUE THREAD

**Issue by hidaytrahman** [masroorejaz/react-simple-captcha#23]
Tried to load both parser.

```ERROR in ./node_modules/react-html-parser/node_modules/htmlparser2/lib/WritableStream.js 9:13-37

Module not found: Error: Can't resolve 'buffer' in 'learn/node_modules/react-html-parser/node_modules/htmlparser2/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }
```

**Comment by masroorejaz** [comment]
I haven't tested it with React 18 as of now.

But what I have Googled so far I think the issue lies somewhere else. Try installing these two npm and let me know if this resolves your issue:

`npm install assert --save`
`npm install buffer --save`

**Comment by hidaytrahman** [comment]
Thank you @masroorejaz. Is there any plan to remove these dependencies

**Comment by hidaytrahman** [comment]
Closing this with the implementation of React 18 (hooks)

```
import {
  loadCaptchaEnginge,
  LoadCanvasTemplate,
  LoadCanvasTemplateNoReload,
  validateCaptcha,
} from "react-simple-captcha";
```
`loadCaptchaEnginge(6)` (You can change 6 to the number of captcha characters you want) in `useEffect()`
```
  useEffect(() => {
    loadCaptchaEnginge(6);
  }, []);
```

**Comment by masroorejaz** [comment]
> Thank you @masroorejaz. Is there any plan to remove these dependencies

You are most welcome. Will see in the future.

**Comment by Mridul5300** [comment]
useEffect(() => {
    // Load only numbers for captcha
    loadCaptchaEnginge(6, "white", "red", "0123456789",); // '0123456789' ensures only numbers
  }, []);What is the problem with the captcha number not appearing here?

**Comment by Mridul5300** [comment]
> useEffect(() => { // Load only numbers for captcha loadCaptchaEnginge(6, "white", "red", "0123456789",); // '0123456789' ensures only numbers }, []);What is the problem with the captcha number not appearing here?
