### ISSUE TITLE
remove color style from link

### ISSUE THREAD

**Issue by nordbit** [masroorejaz/react-simple-captcha#24]
```
let LoadCanvasTemplate_HTML = "<div><canvas id=\"canv\"></canvas><div><a id=\"reload_href\"  style=\"cursor: pointer; color: blue\">Reload Captcha</a></div></div>";
```
Link styled inline is hard to override, please leave it for user css
Color blue looks bad on blue background

**Comment by masroorejaz** [comment]
Kindly check the demo here:

https://scriptse.com/react-simple-captcha-demo/

You can change both background and font colors to your liking.
