### ISSUE TITLE
Could not find a declaration file for react-simple-captcha

### ISSUE THREAD

**Issue by edotappstore** [masroorejaz/react-simple-captcha#25]
Hi 

I am getting the below mentioned error after installing latest version of react-simple-captcha : 9.0.2
![image](https://user-images.githubusercontent.com/98312418/210524299-7850fd50-a84a-4856-92a3-715ce91ec917.png)

![image](https://user-images.githubusercontent.com/98312418/210521189-0f94a25d-567b-4021-a1b2-f1c104985de6.png)

anything i am missing ?

Thank you

**Comment by masroorejaz** [comment]
```
npm install assert --save
npm install buffer --save
```

**Comment by edotappstore** [comment]
Thank you @masroorejaz 
that fixed the issue

**Comment by masroorejaz** [comment]
This is the recurring problem in ReactJS 18.
I will add these two npm as my Dependency packages in upcoming release.
