### ISSUE TITLE
can't use string variable in reloadText property

### ISSUE THREAD

**Issue by amirshnll** [masroorejaz/react-simple-captcha#27]
Hello @masroorejaz ,
In `reloadText` of `LoadCanvasTemplate`, I can't use a variable with a string. I load all of my string as a JSON file in page:

```
import STRINGES from "./string.json";
.
.
.
<LoadCanvasTemplate reloadText={STRINGES.reload} />
```

**Comment by masroorejaz** [comment]
Actually random string generation is already built-in function in react-simple-captcha.

Kindly read all the **Optional Changes** in [Readme file](https://www.npmjs.com/package/react-simple-captcha)

Simply use **_loadCaptchaEnginge(Number_Of_Captcha_Charcters, Background_Color);_** as mentioned in Readme File and it will generate random string automatically.

**Comment by amirshnll** [comment]
no no no,
I want to read reload link text from a file.

**Comment by masroorejaz** [comment]
Actually that's currently not possible in this captcha.

Also there are plenty of options like Numeric Only, Alphabets or Special Characters only that will fulfilled your desired output in Captcha.

If you still having problem then kindly share a screenshot with detials.

**Comment by amirshnll** [comment]
Thank you for replying fast.

To prevent hard code Persian (Farsi) characters immediately, I create a JSON file for saving my web app strings. and I want read value of the `reloadText` property instead of the hardcode inside my file:

hardcoded version
```
<LoadCanvasTemplate reloadText={"کدجدید"} />
````

i want this:

```
import STRINGES from "./string.json";
.
.
.
<LoadCanvasTemplate reloadText={STRINGES.reload} />
````
json file
```
{
"reload":"کدجدید"
}
```

In the render page, your library has not loaded my string and loaded the default string for `reloadText.`

**Comment by masroorejaz** [comment]
You can get value from json file in a string and display it using that string.

Currently what you are looking for it's not possible in the current version. You can however make changes the code accordingly as the whole code is uploaded on GitHub.

Thank you.

**Comment by amirshnll** [comment]
Thank you.
I feel you can fix this problem with localization
