### ISSUE TITLE
could you update react-html-parser with latest module "html-react-parser"

### ISSUE THREAD

**Issue by amujuruprasad** [masroorejaz/react-simple-captcha#29]

**Comment by masroorejaz** [comment]
Is it causing any problem with the current version?

**Comment by amujuruprasad** [comment]
`npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-html-parser@2.0.2
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   8 more (react-dom, react-icons, react-loading-overlay-ts, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-html-parser@2.0.2
npm WARN node_modules/react-simple-captcha/node_modules/react-html-parser
npm WARN   react-html-parser@"^2.0.2" from react-simple-captcha@9.0.13
npm WARN   node_modules/react-simple-captcha
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-html-parser@2.0.2
npm WARN   node_modules/react-simple-captcha/node_modules/react-html-parser
npm WARN     react-html-parser@"^2.0.2" from react-simple-captcha@9.0.13
npm WARN     node_modules/react-simple-captcha
`
This warning is coming

**Comment by masroorejaz** [comment]
I guess it's only showing while installing.
Is captcha working fine?

**Comment by masroorejaz** [comment]
Okay.
Will update it once I have got some time.
Super busy right now.
Also this is the ongoing issue with npm libraries they depreciate the old libraries in few months.

Thank you for pointing out and I will resolve it once I have got some time.
