### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ReactNewbie-J** [masroorejaz/react-simple-captcha#3]
I followed the steps and when I added the < LoadCanvasTemplate /> or < LoadCanvasTemplateNoReload />, I'm getting this error. SyntaxError: Cannot use import statement outside a module. I'm using Next.js 9.5.5
![image](https://user-images.githubusercontent.com/80018491/117625134-48dd0b00-b1a8-11eb-8088-3d875ca44c3c.png)

**Comment by masroorejaz** [comment]
Hello,

I haven't tested it or neither work in Next.js

Therefore I am really sorry I can't help you on this issue.

Thank you.

**Comment by masroorejaz** [comment]
Hello,

It is not yet compatible with Next.js.

Maybe in future release I will make it compatible with Next.js.

Thank you.

**Comment by ReactNewbie-J** [comment]
Thank You

[image: Logo] <https://www.aa-rmd.com/> *Jasper Ejoc*
Programmer | Anthony and Associates RMD
140 Broadway 46th Floor
Lower Manhattan, New York, NY 10005
*Office No*:1 800 448 5849
*Email*: ***@***.***
*Website*: www.aa-rmd.com
