### ISSUE TITLE
Having this issue with Vite, though code seems to be working as intended.

### ISSUE THREAD

**Issue by rdhermawan** [masroorejaz/react-simple-captcha#30]
Module "events" has been externalized for browser compatibility. Cannot access "events.EventEmitter" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

**Comment by masroorejaz** [comment]
Haven't tested it with Vite yet.

**Comment by rdhermawan** [comment]
okk, thanks
