### ISSUE TITLE
Can't be used with TypeScript

### ISSUE THREAD

**Issue by jacksrm** [masroorejaz/react-simple-captcha#33]
Until now I can't find a good way to use it with typescript cause there's no type exported in the lib.

**Comment by masroorejaz** [comment]
Currently it's not compatible with typescript.

Thank you.

**Comment by Stuart88** [comment]
In your project source directory create a `types` folder and make a types file so typescript will not hit an error.


```
/// \src
/// ..\types
/// ..\..\react-simple-captcha.d.ts

declare module 'react-simple-captcha';
```
Now typescript lets you use it without types.

**Comment by masroorejaz** [comment]
@Stuart88 Thank you for providing the solution 

I am pinning down your solution link to the main page of NPM.

Again thank you so much.
