### ISSUE TITLE
Not able to change the background color of captcha

### ISSUE THREAD

**Issue by nitesh585** [masroorejaz/react-simple-captcha#6]
I am creating a function-based react component and loading Enginge inside useEffect method.

```
  useEffect(() => {
    loadCaptchaEnginge(5, "blue");
  }, []);
```

But, when I tried to change the background color of the captcha it didn't work.

**Comment by masroorejaz** [comment]
It will not work in useEffect. Use it in componentDidMount 

componentDidMount () {
    loadCaptchaEnginge((5, "blue"); 
 };

**Comment by nitesh585** [comment]
@masroorejaz  I have already mentioned that I am creating a function-based component, not a class-based. And, In the [docs of react](https://reactjs.org/docs/hooks-effect.html) it is clearly mentioned that:
_If you’re familiar with React class lifecycle methods, you can think of useEffect Hook as componentDidMount, componentDidUpdate, and componentWillUnmount combined._

Then, It should work with useEffect too.

**Comment by masroorejaz** [comment]
I haven't tested it or work a lot with useEffect.

So really sorry can't help you there.
