### ISSUE TITLE
Spelling error at "Reload captcha"

### ISSUE THREAD

**Issue by lucianourgal** [masroorejaz/react-simple-captcha#8]
Hey! Can you please fix this spelling error?

It's showing "Reload Captach". It's supposed to be "Reload Captcha"

![image](https://user-images.githubusercontent.com/7585947/123340788-2cf8b300-d523-11eb-9a59-17b09897ed90.png)

**Comment by masroorejaz** [comment]
It is indeed showing "Reload Captcha" 

Also if you are facing this spelling problem then you can change the spelling with the following:

< LoadCanvasTemplate reloadText="Reload Captcha" />
